# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0551562a8280f4b16bb527e9b91ead5c78c43c3726f56cdddb2803765859ba6543be945942790e37102a1035b41cb9422c0e6bb1879a2809c8ba3e9b4249aa2

test:
  secret_key_base: 9e9b5236ac358aeb4a4c699ed9a1b155a81f7926045c192c99476673c7f1d2b795ba253d2e2357bb931bf4a935fd3fb27073bc5a82907db75611dcdedc368619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
